### ISSUE TITLE
Python 3 compat

### ISSUE THREAD

**Issue by saily** [mgaitan/sphinxcontrib-mermaid#1]
Thanks for this great plugin! Since more and more projects are moving forward to Python 3 and Sphinx is also working with py3 now, could we ensure this plugin works with py3 as well?

I'm getting following exception: 

```
Exception occurred:
  File "/Users/daniel/Workspace/zg_ecommerce/lib/python3.5/site-packages/sphinxcontrib/mermaid.py", line 145, in render_mm
    t.write(code)
TypeError: write() argument must be str, not bytes
```

**Comment by shakfu** [comment]
Check out my PR #2 for a quick python3 fix for html only.
