### ISSUE TITLE
Incorrect sequence rendering

### ISSUE THREAD

**Issue by MrOneTwo** [mgaitan/sphinxcontrib-mermaid#105]
Can't really figure out why this doesn't render correctly:

```
.. mermaid::

  sequenceDiagram
      participant H as Host
      participant D as Device
      H->>D: Setup Token
      H->>D: Data0 Packet
```

![image](https://user-images.githubusercontent.com/9691310/214638494-5da5f2f8-5f76-4db1-a3c0-2a3b84dd2cc4.png)

**Comment by timkpaine** [comment]
Can't repro on 1.0, after that is released if the issue persists please open a new ticket
