### ISSUE TITLE
Mermaid renders text with no errors

### ISSUE THREAD

**Issue by Venkat-Rajgopal** [mgaitan/sphinxcontrib-mermaid#113]
Running the mermaid extension results in a plain text with no errors during the sphinx-autobuild. Following are the versions I am using

```
sphinxcontrib-mermaid==0.8.1
sphinx= ">=5<6"
myst-parser = "0.19.1"
```

Extensions
```
extensions = ["myst_parser",
              "sphinx_design",
              "sphinxcontrib.mermaid"]
```

In the markdown. 

```{mermaid}
    sequenceDiagram
      participant Alice
      participant Bob
      Alice->John: Hello John, how are you?
      
```

Result in a plain text like this. 

sequenceDiagram participant Alice participant Bob Alice->John: Hello John, how are you?

With no errors this is hard to debug. Any pointers here ?

**Comment by andreidci** [comment]
I am facing the same issue , it worked fine for months and now instead of seeing the diagram, the plain text is shown in the html page.

I am using:
`sphinx==5.3.0,
myst-parser==0.18.1,
sphinxcontrib-mermaid==0.7.1
`

Extensions 
`
extensions = [
    "sphinx.ext.autosectionlabel", 
    "sphinx.ext.autodoc",  
    "sphinx.ext.napoleon", 
    "myst_parser",  
    "sphinxcontrib.mermaid", 
]
`

Sample from md file :

```
## Normal scenario

```{mermaid}
sequenceDiagram
    participant C as Caller ( C )
    participant T as Target ( T )
```
(closing ``` are also present)

**Comment by andreidci** [comment]
I just now tried bumping up the versions and it's working again 👍 

Now using:
`
sphinx==6.1.3, myst-parser==1.0.0, sphinxcontrib-mermaid==0.8.1 
`

So seems like it's an issue in either myst-parser or Sphinx

**Comment by Venkat-Rajgopal** [comment]
> I just now tried bumping up the versions and it's working again 👍
> 
> Now using: `sphinx==6.1.3, myst-parser==1.0.0, sphinxcontrib-mermaid==0.8.1 `
> 
> So seems like it's an issue in either myst-parser or Sphinx

have bumped the same versions. Still no change. Is there a way to rebuilt sphinx again. It was working then suddenly stopped rendering during version changes.

**Comment by Venkat-Rajgopal** [comment]
Looks like this [fix](https://github.com/mgaitan/sphinxcontrib-mermaid/pull/111) needs to be merged.

**Comment by slavakx** [comment]
> I just now tried bumping up the versions and it's working again 👍
> 
> Now using: `sphinx==6.1.3, myst-parser==1.0.0, sphinxcontrib-mermaid==0.8.1 `
> 
> So seems like it's an issue in either myst-parser or Sphinx

Still have this problem. 
I am using `sphinx==6.2.1, myst-parser==1.0.0, sphinxcontrib-mermaid==0.8.1 `

**Comment by Venkat-Rajgopal** [comment]
Same here

**Comment by fumitoh** [comment]
Isn't this because of nbsphinx as reported in #74?
Setting `nbsphinx_requirejs_path = ''` in `conf.py` solved the issue as recommended [here](https://github.com/spatialaudio/nbsphinx/issues/678).

**Comment by timkpaine** [comment]
Cannot reproduce
