### ISSUE TITLE
This package raises DeprecationWarnings

### ISSUE THREAD

**Issue by mdczaplicki** [mgaitan/sphinxcontrib-mermaid#119]
```
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
```

Any chances to get rid of this?

**Comment by mgaitan** [comment]
Sure, it's needed. Actually we need a complete modernization, migrating to `pyproject.toml`

**Comment by lukasjuhrich** [comment]
Is this fixed by https://github.com/mgaitan/sphinxcontrib-mermaid/commit/dea2e76f1c9176b45aa1db7a9e8a7841a6a9a6f6?

**Comment by timkpaine** [comment]
yes this should be done once https://github.com/mgaitan/sphinxcontrib-mermaid/pull/153 gets released
