### ISSUE TITLE
zoom is not working

### ISSUE THREAD

**Issue by pancodia** [mgaitan/sphinxcontrib-mermaid#125]
I am using this package to embed a flowchart in my sphinx doc. My mermaid code is in a separate file. I sourced the file as

```
.. mermaid:: ./data_pipeline.mmd
```

In the generated html, I can see the diagram. However, I cannot zoom in or out. 

The following is my configuration for the package in `conf.py`: 

```
# ------------ Mermaid configuration --------------------------------
mermaid_output_format = 'svg'
mermaid_cmd = '/Users/pachao/.asdf/shims/mmdc'
mermaid_d3_zoom = True
``` 

The following are my package versions (I am using pydata-sphinx-theme):

```
$ pip3 show sphinxcontrib-mermaid sphinx
Name: sphinxcontrib-mermaid
Version: 0.9.2

Name: Sphinx
Version: 7.0.1

Name: pydata-sphinx-theme
Version: 0.13.3
```

How would you suggest me to debug the issue?

**Comment by PhorstenkampFuzzy** [comment]
Is the zoom only possible for raw?

**Comment by timkpaine** [comment]
Should work in 1.0, once that is released if the issue persists please open a new ticket
