### ISSUE TITLE
Request: supporting mermaid diagrams directly in a Python docstring

### ISSUE THREAD

**Issue by jamesbraza** [mgaitan/sphinxcontrib-mermaid#129]
Lets say I have a simple Mermaid `flowchart`:

```none
flowchart TD
    A["Foo"]
```

The request: supporting placing a Mermaid diagram in a Python docstring:

```python
def foo() -> None:
    """
    Some Google-style docstring.

    Diagram:
        flowchart TD
            A["Foo"]
    """
```

And having it recognized by `sphinx-build`, and placed into generated docs for the function `foo`.  I think this request may entail creating a new Sphinx builder.

**Comment by mgaitan** [comment]
I guess this should work https://github.com/sphinx-extensions2/sphinx-autodoc2 , could you try it ?  the docstring there could be  any source renderable by sphinx. . 


so, for instance using myst your code will looks like this 

````
def foo() -> None:
    """
    Some Google-style docstring.

    ```mermaid
        flowchart TD
            A["Foo"]
     ```       
    """
````
the conf.py

```python
extensions = [
    "myst_parser",
    "sphinxcontrib.mermaid",
    "autodoc2",
    ...
]

autodoc2_packages = [
    {
        "path": "path/to/your/code",
        "auto_mode": False,
    },
]
autodoc2_render_plugin = "myst"
```

and the doc page where you want to include the ref

````
# page title

```{autodoc2-object} path.to.your.code.foo
```
````

**Comment by jamesbraza** [comment]
Actually, this worked 😄:

```python
def foo() -> None:
    """
    Some Google-style docstring.

    .. mermaid::
       flowchart TD
           A["Foo"]
    """
```

Turns out, this is already fully supported!  Feel free to close this out...

**Comment by mgaitan** [comment]
cool!
