### ISSUE TITLE
Support for the new Mermaid CLI

### ISSUE THREAD

**Issue by karl-sjogren** [mgaitan/sphinxcontrib-mermaid#13]
I just installed this extension and ran into problems immediately. The used `mermaid-cli` is deprecated and the new official have a completely different syntax.

The official CLI is available from https://github.com/mermaidjs/mermaid.cli and for starters the command is now `mmdc` instead of `mermaid`. The output type is determined by the extension of the output file, there are no flags for `verbose`, `phantomPath ` or `sequenceConfig`.

I did a short attempt to get it working but my knowledge of Python and Sphinx extensions wasn't really enough. Ideally this could be supported by checking the mermaid_cmd option if we should use `mermaid` or `mmdc` to keep it backwards compatible.

**Comment by bastiedotorg** [comment]
see #14

**Comment by mgaitan** [comment]
fixed in #14
