### ISSUE TITLE
Allow use of local d3 distribution

### ISSUE THREAD

**Issue by Rubyfi** [mgaitan/sphinxcontrib-mermaid#142]
I'd be interested in a feature that allows users to load d3.js locally instead of from unpkg (similar to loading mermaid.js locally).
Of course, I'd be happy to contribute this change myself.

Is there a dependency to a specific version of d3 or is it just the latest by default?
I'd go with allowing to specify a desired version via a new config flag ``d3_version`` and basically use the same approach that is used to load mermaid.js.

**Comment by mgaitan** [comment]
this would be great. go ahead!
