### ISSUE TITLE
Sequence diagram empty directive marked as incorrect mermaidJS

### ISSUE THREAD

**Issue by MaxWinsemius** [mgaitan/sphinxcontrib-mermaid#143]
I noticed when working on sequenceDiagrams, that the method of rendering does not match with the [mermaid live renderer](https://mermaid.live/edit#pako:eNpNjjEOwjAMRa9SeQ4XyNCJlYkNRUJuYtoIYpc0GVDVu2OKgvD07fdlvRW8BAILCz0rsadjxDFjctzpsLIrHvp-D4PtvKREXP7o0CjaDgwkyglj0Ifrp-SgTJTIgdUYMN8dON60h7XI-cUebMmVDGSp4wT2ho9FtzoHLE3ld6UQi-TT13fXNjAjX0RaZ3sDHr1F4A).

When using the following snippet:

```
sequenceDiagram
    node_a->>node_b: comment
    node_b->>node_a: 
```

(Note the space at the end of line 3)

I get the following render from the live renderer:

![image](https://github.com/mgaitan/sphinxcontrib-mermaid/assets/12040226/f5d5b608-3dd2-4e99-9d9f-5ad126261ee8)

But an error if build using sphinx:

![image](https://github.com/mgaitan/sphinxcontrib-mermaid/assets/12040226/4d4edcc3-7aed-4b86-b42a-7803a36620d6)

Now I do not know if this syntax is even supported on purpose by Mermaid, since I didn't find any examples of that either and if I remove the space on line 3 it also fails.

**Comment by timkpaine** [comment]
This is a bit of a quirk of how that website works. That example does NOT work on the mermaid main docs. However, easy to see why, it is not valid for that diagram type to have a space as the comment, but the editor encodes it. You can do the same with this

````
```mermaid
sequenceDiagram
    node_a->>node_b: comment
    node_b->>node_a: #nbsp;
```
````

```mermaid
sequenceDiagram
    node_a->>node_b: comment
    node_b->>node_a: #nbsp;
```
