### ISSUE TITLE
The instructions doesn't work for Markdown files

### ISSUE THREAD

**Issue by monajalal** [mgaitan/sphinxcontrib-mermaid#146]
I have a file `simple_mermaid.md`

# Simple Mermaid

```{mermaid}

    sequenceDiagram
      participant Alice
      participant Bob
      Alice->John: Hello John, how are you?
```

(code block indentation is not working correct here but I copied this )

![Screenshot from 2024-08-08 08-39-47](https://github.com/user-attachments/assets/47003cc5-f728-455c-82fd-3b413ac8f47d)

However, after rendering it, it doesn't render correctly and I see this.
![image](https://github.com/user-attachments/assets/92c0200b-12e4-4af1-a934-1d25a27b073c)

I have both of `sphinxcontrib-mermaid` and `myst_parser` extensions in `conf.py`. I don't intend to use mermaid charts inside an .rst file and need them to be inside a .md file.

How can I fix this problem?

**Comment by timkpaine** [comment]
I'm not able to reproduce, could you make a repo/gist with your `conf.py` and your markdown file in it?

**Comment by PhorstenkampFuzzy** [comment]
Do you use `nbsphinx`?

**Comment by timkpaine** [comment]
I use https://myst-nb.readthedocs.io/en/latest/

**Comment by PhorstenkampFuzzy** [comment]
I had a requests.min.js in my script list im html head added by nbsphinx. After removal of nbsphinx it rendered the plots. So possibly ...

**Comment by timkpaine** [comment]
Sounds like its not a problem with this library, but instead with nbsphinx

**Comment by PhorstenkampFuzzy** [comment]
This was in my case. He is useing something else that may or may not be the same conflict.
