### ISSUE TITLE
Broken with Sphinx 8.1.0

### ISSUE THREAD

**Issue by jacobtomlinson** [mgaitan/sphinxcontrib-mermaid#160]
As of the sphinx `8.1.0` release we are now seeing build failures that seem to be coming from this plugin.

```
Running Sphinx v8.1.0
loading translations [en]... done

Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ExtensionError' from 'sphinx.util' (.../miniforge3/envs/deployment-docs-dev/lib/python3.12/site-packages/sphinx/util/__init__.py))
make: *** [dirhtml] Error 2
```

**Comment by Paebbels** [comment]
It looks like Sphinx 8.1.x moved `ExtensionError` from `sphinx.util` to `sphinx.errors`, but according to https://github.com/mgaitan/sphinxcontrib-mermaid/pull/161#issuecomment-2407583482, it was moved long time ago and `sphinxcontrib-mermaid` uses a long outdated API.
