### ISSUE TITLE
Text content of some valid Mermaid nodes fails to render in Sphinx

### ISSUE THREAD

**Issue by jimratliff** [mgaitan/sphinxcontrib-mermaid#164]
Environment:
- Sphinx: 8.1.3
- sphinxcontrib-mermaid: 1.0.0
- Mermaid.js: 8.14.0 (default version)
- Configuration: sphinxcontrib.mermaid enabled in extensions

Description:
The text inside certain Mermaid nodes fails to render 
in Sphinx, while the exact same diagram renders correctly on mermaid.live. Initial testing suggests the issue might be related to text content complexity or length, but the root cause is unclear.

See pair of screenshots: failure in Sphinx but success at Mermaid.live.

Minimal Reproducible Example:
```rst
.. mermaid::

   graph TD
       A[["OrderError_MissingQuantity"]]
       B{{"Split at underscore again"}}
       C[["'OrderError'"]]
       D[["'MissingQuantity'"]]
       E{{"Split at CamelCase"}}
       F{{"Split at CamelCase"}}
       G[["'Order Error'"]]
       H[["'Missing Quantity'"]]
       I{{"Join Primary (Secondary Phrases)"}}
       J[["Order Error (Missing Quantity)"]]

       A --> B
       B --> C
       B --> D
       C --> E
       D --> F
       E --> G
       F --> H
       G --> I
       H --> I
       I --> J
```

```mermaid
   graph TD
       A[["OrderError_MissingQuantity"]]
       B{{"Split at underscore again"}}
       C[["'OrderError'"]]
       D[["'MissingQuantity'"]]
       E{{"Split at CamelCase"}}
       F{{"Split at CamelCase"}}
       G[["'Order Error'"]]
       H[["'Missing Quantity'"]]
       I{{"Join Primary (Secondary Phrases)"}}
       J[["Order Error (Missing Quantity)"]]

       A --> B
       B --> C
       B --> D
       C --> E
       D --> F
       E --> G
       F --> H
       G --> I
       H --> I
       I --> J
```

  
<img width="695" alt="Screenshot_success_at_Mermaid-live" src="https://github.com/user-attachments/assets/ed8e3ad7-64d9-4ecf-9e52-c0ab75fa5d88">
<img width="439" alt="Screenshot_Mermaid-Sphinx_fail" src="https://github.com/user-attachments/assets/93b630c0-d479-44ff-9bf3-1a4fd3057251">

**Comment by timkpaine** [comment]
Just tested locally, here is what I see:

<img width="478" alt="Screenshot 2024-11-10 at 23 29 11" src="https://github.com/user-attachments/assets/925536cc-c14e-4ed2-bbc6-888466b2653d">

**Comment by timkpaine** [comment]
Cannot repro, please provide an `rst/md` file and list any customizations/extensions

**Comment by timkpaine** [comment]
here is what I see: 

<img width="1172" alt="Screenshot 2024-11-10 at 23 48 23" src="https://github.com/user-attachments/assets/63ec4e59-2927-44a0-9ca3-dffcd703c9b9">


tested sphinx 7 and 8, latest autoclasstoc and piccolo_theme

**Comment by jimratliff** [comment]
Thanks for trying. I'll chalk it up a mystery of the universe, and use a .png workaround for this.

**Comment by timkpaine** [comment]
I would try to upgrade whatever deps here you can to later versions and check for any errant unmatched things in the file. I've also had at least 1 other issue before where the order of extensions meant that some character sequences were getting transformed by other extensions before they hit this extension.
