### ISSUE TITLE
Discussion: PdfCrop

### ISSUE THREAD

**Issue by bastiedotorg** [mgaitan/sphinxcontrib-mermaid#17]
Hi,

I created a patch to use pdfcrop in latexmode.
https://github.com/bastiedotorg/sphinxcontrib-mermaid/pull/1

Is this useful to you or would you reject that patch?

**Comment by mgaitan** [comment]
seems useful, open the PR on this repo!

**Comment by mgaitan** [comment]
merged #19 . Thanks!
