### ISSUE TITLE
Mermaid version update

### ISSUE THREAD

**Issue by derekmerck** [mgaitan/sphinxcontrib-mermaid#20]
Hi -- thanks for your work on the mermaid sphinx bridge!  You might consider updating the Mermaid version in `mermaid.py` to "8.0.0-rc.6".  It got bumped a couple of weeks ago, and there are some useful new features (xaxis marks on timelines).  

https://github.com/knsv/mermaid/issues/643

**Comment by jobec** [comment]
I always make my graphs via the online editor here: https://mermaidjs.github.io/mermaid-live-editor which uses a newer version.
Maybe it's a better idea to make the version configurable? Because in the mean while 8.2.1 is out already.

**Comment by IceflowRE** [comment]
Bump and can you release a new version on PyPi?

**Comment by mgaitan** [comment]
now the default version is always the latest on the CDN.
