### ISSUE TITLE
Changing custom classes /themes is ignored

### ISSUE THREAD

**Issue by ccamara** [mgaitan/sphinxcontrib-mermaid#24]
I have the following diagram:

```
.. mermaid::
  :caption: Diagrama de metodología
  :alt: Diagrama de metodología
  :align: center


  graph TD
    A(Building Part)--PBAbp-->PBA_inici
    B(Cadastral Parcel)--PBAcp-->PBA_inici
    C(Working Area)--"(Nombre de capa varia)"-->PBA_inici
    PBA_inici[PBA_inici]--PBbpcp-->PB_topologia[PB_topologia]
    PBA_inici[PBA_inici]-.PBbp_selected.->Backup>Capas de Backup]
    PBA_inici[PBA_inici]-.PBcp_selected.->Backup>Capas de Backup]
    subgraph Topologia
      PB_topologia[PB_topologia]--PBAr-->Rev_top[Revision topologia manual]
      click PB_topologia "#revision-topologica" "Ver info detallada"
    end
    subgraph Orientaciones
      Rev_top--"Checked_PBAr"-->Pol2Line[Modelo Pol2Line]

    end
    classDef BackupLayers fill:#e7bbbb,stroke:#880000,stroke-width:1px
    class Backup BackupLayers
    classDef Models fill:#bbe7e2,stroke:#008878
    class PBA_inici,PB_topologia Models
```

The expected result would be that from mermaid online editor ([see link](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG5BKEJ1aWxkaW5nIFBhcnQpLS1QQkFicC0tPlBCQV9pbmljaVxuQihDYWRhc3RyYWwgUGFyY2VsKS0tUEJBY3AtLT5QQkFfaW5pY2lcbkMoV29ya2luZyBBcmVhKS0tXCIoTm9tYnJlIGRlIGNhcGEgdmFyaWEpXCItLT5QQkFfaW5pY2lcblBCQV9pbmljaVtQQkFfaW5pY2ldLS1QQmJwY3AtLT5QQl90b3BvbG9naWFbUEJfdG9wb2xvZ2lhXVxuUEJBX2luaWNpW1BCQV9pbmljaV0tLlBCYnBfc2VsZWN0ZWQuLT5CYWNrdXA-Q2FwYXMgZGUgQmFja3VwXVxuUEJBX2luaWNpW1BCQV9pbmljaV0tLlBCY3Bfc2VsZWN0ZWQuLT5CYWNrdXA-Q2FwYXMgZGUgQmFja3VwXVxuc3ViZ3JhcGggVG9wb2xvZ2lhXG5QQl90b3BvbG9naWFbUEJfdG9wb2xvZ2lhXS0tUEJBci0tPlJldl90b3BbUmV2aXNpw7NuIHRvcG9sb2fDrWEgbWFudWFsXTtcbmNsaWNrIFBCX3RvcG9sb2dpYSBcIiNyZXZpc2lvbi10b3BvbG9naWNhXCIgXCJUaGlzIGlzIGEgbGlua1wiXG5lbmRcbnN1YmdyYXBoIE9yaWVudGFjaW9uZXNcbiAgICAgIFJldl90b3AtLVwiQ2hlY2tlZF9QQkFyXCItLT5Qb2wyTGluZVtNb2RlbG8gUG9sMkxpbmVdXG5lbmRcblxuY2xhc3NEZWYgQmFja3VwTGF5ZXJzIGZpbGw6I2U3YmJiYixzdHJva2U6Izg4MDAwMCxzdHJva2Utd2lkdGg6MXB4O1xuY2xhc3MgQmFja3VwIEJhY2t1cExheWVycztcblxuY2xhc3NEZWYgTW9kZWxzIGZpbGw6I2JiZTdlMixzdHJva2U6IzAwODg3ODtcbmNsYXNzIFBCQV9pbmljaSxQQl90b3BvbG9naWEsUG9sMkxpbmUgTW9kZWxzO1xuIiwibWVybWFpZCI6eyJ0aGVtZSI6Im5ldXRyYWwifX0))

![Expected result](https://screenshotscdn.firefoxusercontent.com/images/557ee762-c57f-421f-8fc7-0eb72a92a864.png)

But instead, I get the following one, which ignores my custom classes: 

![Actual result, ignoring custom classes](https://screenshotscdn.firefoxusercontent.com/images/6c9fce6c-493a-4f73-b66c-f351d23b631f.png)

Furthermore, I would like to use the `neutral` built-in theme, but despite the readme file states that it is possible using `mermaid_params`, I do not know where and how should I pass the theme parameter so mermaid is built when building a sphinx page.

**Comment by drammock** [comment]
I think this issue would go away if the version definition [here](https://github.com/mgaitan/sphinxcontrib-mermaid/blob/master/sphinxcontrib/mermaid.py#L35) changed to `8.0.0` (no longer a candidate release) and a new version was released to PyPI.  The current PyPI version uses mermaid `7.1.0`.

**Comment by pocc** [comment]
Confirming this is an issue with the PyPI version. Workaround is to install directly from github:

```bash
pip install git+https://github.com/mgaitan/sphinxcontrib-mermaid --upgrade
```
