### ISSUE TITLE
Please provide source distribution via PyPI.

### ISSUE THREAD

**Issue by matjam** [mgaitan/sphinxcontrib-mermaid#25]
as per title;

https://pypi.org/project/sphinxcontrib-mermaid/#files

need tgz source distribution.

Thanks :-)

**Comment by mgaitan** [comment]
sure, not a problem. I'll do it for the next release. 
But just curious. what's the rationale behind this request? isn't enough github's zip file of each tag of this repo? what is particularly useful the tar.gz in pypi?

**Comment by matjam** [comment]
Thanks!

We have a build system which when we add a given package to the build system, it looks at the official source package on PyPI and uses those to build packages for internal consumption.

Thats about as much detail as I know - I'm new here, haha :-)

**Comment by mgaitan** [comment]
released 0.6 in wheel and source formats
