### ISSUE TITLE
Supporting markdown parcing

### ISSUE THREAD

**Issue by evangelos-ai** [mgaitan/sphinxcontrib-mermaid#26]

**Comment by mgaitan** [comment]
please, describe what this issue is about.

**Comment by evangelos-ai** [comment]
Hi @mgaitan , 
it would be nice if by installign the sphinxcontrib-mermaid package, to be possible to use the mermaid directive to markdown files like this : 
`
```mermaid
graph LR
    T[To Do] --> IP[In Progress]
    IP --> IR[In Review]
    IR --> D[Done]
    IP --> B[Blocked]
    B --> IP[In Progress]
    T --> C[Closed]
```
`

and then when a user does `make html` to be about to see these diagrams.

Does this make any sense ? I think currently you are only able to use this directive from rst files

**Comment by jvinai** [comment]
I have the same issue, i cant use
```
```mermaid ...````
```

**Comment by mgaitan** [comment]
I've just documented how to support mermaid in markdown via `eval_rst`. It's not a real mermaid support. 
https://github.com/mgaitan/sphinxcontrib-mermaid#markdown-support
