### ISSUE TITLE
offline JS file

### ISSUE THREAD

**Issue by slavkoja** [mgaitan/sphinxcontrib-mermaid#29]
Please, allow to use offline JS file.

Currently the JS's URL is linked to online page and i cannot see way to change it to use offline copy, other than change code. Or i miss something?

Can you please add config value for this? E.g. if unset (default) it will use online URL as now, if set to same path, it will use this path relative to static folder.

**Comment by AndreasSchirm** [comment]
I need this feature too.

Currently there is a dependency to <https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js>
from <https://github.com/mgaitan/sphinxcontrib-mermaid/blob/master/sphinxcontrib/mermaid.py#L39>

It would really great to handle this dependency by myself.

**Comment by mgaitan** [comment]
great idea. Do you dare to send a PR?
