### ISSUE TITLE
Class not working in raw output format

### ISSUE THREAD

**Issue by monsieurTut** [mgaitan/sphinxcontrib-mermaid#35]
Hi,

I use sphinxcontrib-mermaid to write documentation for my projects that I then publish as HTML. It works quite well, generally better than other tools I have tried, but sometimes I would like to use classes on the nodes in flowcharts, to change the background colour for instance.

Mermaid.js allows to define classes inside a diagram statement with the `classDef` attribute. Here is an example:

```
graph TB
  s((Start))
  e((End))
     
  s --> e
     
  classDef Foo fill:#66ccff;
  class s Foo;
```

This should (at least it does with mermaid.cli) render as :

![flowchart](https://user-images.githubusercontent.com/6123109/68299409-eb8c6900-009b-11ea-8d12-97dc72d4a2eb.png)

But when using raw output format with sphinxcontrib-mermaid (which is convenient since it does not require to install mermaid.cli), my start node is not colored. I assume that is because the CSS code defining the styling of the class Foo is not included in the HTML page.

I believe a workaround would be to create my own CSS stylesheet, with definitions of my class styles, and configure Sphinx to use it. But it would be great if sphinxcontrib-mermaid could handle the `classDef` by itself.

**Comment by MatinF** [comment]
Would also like to see this resolved

**Comment by mgaitan** [comment]
This seems to be invalidad in current versions with latest mermaid lib.
