### ISSUE TITLE
New release and update package on PyPi

### ISSUE THREAD

**Issue by iceananas** [mgaitan/sphinxcontrib-mermaid#36]
Since the last release (0.3.1), some significant features including parsing parameters for mermaid.cli have been added. I think it would justify a (minor) release so the current status can simply be downloaded with pip.

**Comment by jobec** [comment]
I can only second this.

Also because of #20 : upgrading the mermaid version.

**Comment by ArtFlag** [comment]
A new version would be great. Could we have a second maintainer?

**Comment by mgaitan** [comment]
just released 0.6. anyway, a maintainer would be great. @ArtFlag are u interested?

**Comment by ArtFlag** [comment]
Sorry, I moved away from the Sphinx ecosystem recently.

**Comment by mgaitan** [comment]
no problem., thanks for the update.

**Comment by championshuttler** [comment]
@mgaitan I would like to contribute but can you guide me if possible please what to do
