### ISSUE TITLE
mermaid_params does not work

### ISSUE THREAD

**Issue by ArthurFlag** [mgaitan/sphinxcontrib-mermaid#39]
Hi, 

I added what's from the Readme to my `conf.py` file:

```python
mermaid_params = ['--theme', 'forest', '--width', '600', '--backgroundColor', 'transparent']
```
The build works fine, but I still get the default style. 
Has anyone experienced the same issue?

**Comment by MatinF** [comment]
I experience the same

**Comment by ajdajd** [comment]
It works for me if I set `mermaid_output_format` to png or svg. But I want to use is on raw as well.

**Comment by gitPrinz** [comment]
> The build works fine, but I still get the default style.
> Has anyone experienced the same issue?

I have the same problem with `raw` (the default)!
For `png` or `svg` mermaid.cli is necessary and this seems to be difficult to install (for me on Windows at least).

**Comment by oglops** [comment]
to set theme you use `mermaid_init_js = "mermaid.initialize({startOnLoad:true, theme:'dark'});"`

**Comment by timkpaine** [comment]
Closing as alternate suggestions work, include frontmatter configuration

**Comment by jacopoabramo** [comment]
I have been trying to do something similar with

```
mermaid_init_js = "mermaid.initialize({startOnLoad: true, theme: 'neutral'});"
```

as mentioned in a previous comment but apparently it doesn't seem to work and the theme is left unchanged.

**Comment by timkpaine** [comment]
we can probably make the theme parameterized separately from the initialization script.

**Comment by jacopoabramo** [comment]
I can open a PR for this (not immediatly but I can keep it in my backlog); I just need some pointers on where the extension should be modified
