### ISSUE TITLE
Could not import extension sphinxcontrib.mermaid

### ISSUE THREAD

**Issue by yingma111** [mgaitan/sphinxcontrib-mermaid#46]
Hi,

This is my extensions:
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'recommonmark',
    'breathe',
    'exhale',
    'sphinxcontrib.mermaid'
]

but it happens error: Could not import extension sphinxcontrib.mermaid
Any idea?

**Comment by skidzo** [comment]
I don't know for shure, and it is only vaguely related... but I had problems with the recommonmark extension trying to utilize it in the the way you show.
here is what i did instead:

```
import recommonmark
from recommonmark.parser import CommonMarkParser

source_parsers = {
    '.md': CommonMarkParser
}

source_suffix = ['.rst', '.md']
```

**Comment by gil-obradors** [comment]
Hi @yingma111 
What version are you using?

I confirm that 0.6.2 works fine.

Can you confirm that `sphinxcontrib-mermaid` is installed?

**Comment by jtr109** [comment]
I got a similar problem:

```
Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ENOENT' from 'sphinx.util.osutil'
```

Maybe [the deprecation of ENOENT in 2.0.0](https://www.sphinx-doc.org/en/master/changes.html#:~:text=sphinx.util.osutil.enoent) cause the problem.

**Comment by fernandolamp** [comment]
Hi, This issue is duplicated, verify  issue #72  for workaround

**Comment by jtr109** [comment]
> Hi, This issue is duplicated, verify issue #72 for workaround

Thanks!

There is a better solution in the issue #72 .

**Comment by kloczek** [comment]
You should have look on https://github.com/mgaitan/sphinxcontrib-mermaid/issues/122
