### ISSUE TITLE
Can not set mermaid js url via sphinx

### ISSUE THREAD

**Issue by nojas15** [mgaitan/sphinxcontrib-mermaid#47]
If I want to use a locally installed mermaid version, it is not possible:

https://github.com/mgaitan/sphinxcontrib-mermaid/blob/8679e1e6a7b5485a265bea374983c1d6cd3c4fd0/sphinxcontrib/mermaid.py#L221

Please make `self._mermaid_js_url` changeable via sphinx.

**Comment by mgaitan** [comment]
hi @nojas15 . I agree, this should be configurable.  Are you interested in sending a pull request?

**Comment by strefli3** [comment]
I would like this feature as well, and I'd me happy to contribute that is an option.

**Comment by mgaitan** [comment]
this is currently fixed .
