### ISSUE TITLE
Make `autoclasstree` show all parents, not just direct ones

### ISSUE THREAD

**Issue by sobolevn** [mgaitan/sphinxcontrib-mermaid#48]
Hi! Thanks a lot for a great library!

I am using for our `dry-python/returns` project with great success. But.
I would like to see something like:

```rst
.. autoclasstree: my.module.ClassName
  :full: true
```

**Comment by mgaitan** [comment]
Hi @sobolevn, I'm glad you like this. 

I guess what you need  is doable iterating over `inspect.getclasstree` for each class. but I guess the whole feature needs to be refactored a bit to implement it. 
Let me check it.

**Comment by mgaitan** [comment]
@sobolevn I've just done a complete (much simpler) implementation that support pretty much your approach.  
could you try it and give me some feedback? 

in particular, I'm using the new mermaid's "classDiagram" instead the classic `graph TD`, and I don't know if to support "all the classes on the module" behaviour has any sense to be mantained.

**Comment by sobolevn** [comment]
This might be closed I guess 🙂
