### ISSUE TITLE
Suggestion: automatic class tree for Python libraries

### ISSUE THREAD

**Issue by Zulko** [mgaitan/sphinxcontrib-mermaid#5]
Hey Martin,

I am looking for a way to automatically plot UML diagrams of the inheritance between classes in the Sphinx docs of a library. I think Mermaid would be the classiest solution ([everything else looks a bit old](http://stackoverflow.com/questions/260165/whats-the-best-way-to-generate-a-uml-diagram-from-python-source-code)) and it seems that this project already solves part of the problem, making Mermaid work with Sphinx.

For the automated class tree generation, I wrote a proof of principle script [here](https://gist.github.com/Zulko/e0910cac1b27bcc3a1e6585eaee60121). How difficult do you think it would be to turn this into a easy-to-use sphinx tag ? For instance as follows:

```
.. autoclasstree:
    module: moviepy.editor
    base_module: moviepy
```

and output the full tree in the final presentation:

![result image](https://cloud.githubusercontent.com/assets/1646122/25145211/6f4217b2-2468-11e7-88bd-bda6c0f65408.png)

**Comment by mgaitan** [comment]
nice! it's doable, for sure. Let me hack on it in the next few days.

PS: I'm a very big fun of moviepy (in fact, [my last project](https://github.com/mgaitan/miau) uses it) and specially of your blog. I'm so glad you ask me something here :clinking_glasses:

**Comment by mgaitan** [comment]
@Zulko I've just pushed the first attemp. could you try it?

**Comment by mgaitan** [comment]
the syntax keep 

```
.. autoclasstree: moviepy.editor moviepy
```
