### ISSUE TITLE
syntax error with python2.7 - windows 10

### ISSUE THREAD

**Issue by aaa34169** [mgaitan/sphinxcontrib-mermaid#53]
I ran into mermaid. It s the perfect plugin i  need for my sphinx documentation API. 
I installed the contribution on my windows 10 - python 2.7
when i ran a simple example, this exception appears

`Running Sphinx v1.8.5

Exception occurred:
  File "c:\users\fleboeuf\miniconda3\envs\pycgm2\lib\site-packages\sphinxcontrib\mermaid.py", line 33, in <module>
    from .autoclassdiag import class_diagram
  File "c:\users\fleboeuf\miniconda3\envs\pycgm2\lib\site-packages\sphinxcontrib\autoclassdiag.py", line 6
    def get_classes(*cls_or_modules, strict=False):
                                          ^
SyntaxError: invalid syntax`

could you help me to fix it please ? 

regards 

Fabien

**Comment by mgaitan** [comment]
Hi Fabien, Sphinx dropped support for python 2.7 in  version 2.0 (early 2019), and so this is also a python 3 only extension. 
You could try to use sphinx (preferently a newer version) under python3  or alternatively, use an older version of the extension
