### ISSUE TITLE
Ability to use Mermaid API or add a custom JS script

### ISSUE THREAD

**Issue by mmhoang** [mgaitan/sphinxcontrib-mermaid#54]
I'm looking to add a custom script after the mermaid diagram renders, similar to the examples shown [here](https://mermaid-js.github.io/mermaid/getting-started/usage.html#api-usage). It looks like `_render_mm_html_raw()` is where this would need to happen. Is there an existing capability to support this, or would this be a new feature?

**Comment by mgaitan** [comment]
Hi @mmhoang . sphinx have [a config](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_js_files) to declare custom js files, but I'm afraid they are added before the one of the our plugin. 

So you are right, the way to implement this should be to make the initialization js code in `_render_mm_html_raw` customizable. 

https://github.com/mgaitan/sphinxcontrib-mermaid/blob/master/sphinxcontrib/mermaid.py#L212

probably a new config variable defaulting to `"mermaid.initialize({startOnLoad:true})"` would be enough. 
are you able to open a PR ? 

thanks

**Comment by mmhoang** [comment]
@mgaitan Thanks for the fast response!  I'll experiment with that locally and submit a PR if it works out.

**Comment by mgaitan** [comment]
implemented in v0.6
