### ISSUE TITLE
sphinxcontrib-mermaid uses six but doesn't explicitly require it.

### ISSUE THREAD

**Issue by mwhahaha** [mgaitan/sphinxcontrib-mermaid#57]
Our docs project dropped py2 support so we no longer reference six. But when we attempt to build the docs, loading sphinxcontrib.mermaid fails because six is missing.

docs run-test: commands[0] | sphinx-build -a -E -W -d doc/build/doctrees --keep-going -b html doc/source doc/build/html
setting PATH=/home/zuul/src/opendev.org/openstack/tripleo-docs/.tox/docs/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[4294] /home/zuul/src/opendev.org/openstack/tripleo-docs$ /home/zuul/src/opendev.org/openstack/tripleo-docs/.tox/docs/bin/sphinx-build -a -E -W -d doc/build/doctrees --keep-going -b html doc/source doc/build/html
Running Sphinx v3.3.1

Extension error:
Could not import extension sphinxcontrib.mermaid (exception: No module named 'six')

**Comment by hjensas** [comment]
It probably makes sense to add ``Sphinx  # BSD`` to requirements.txt as well ...
