### ISSUE TITLE
Upload source dist to pypi

### ISSUE THREAD

**Issue by ericpre** [mgaitan/sphinxcontrib-mermaid#60]
The source dist of the last version (0.5) of `sphinxcontrib-mermaid` is not available on pypi and it is necessary to package it on conda-forge - currently at 0.4.

**Comment by mgaitan** [comment]
Just uploaded v0.6

**Comment by ericpre** [comment]
Great, thanks! the conda-forge packages is now up to date:
https://anaconda.org/conda-forge/sphinxcontrib-mermaid/files
