### ISSUE TITLE
can I use mermaid js/css static files locally instead of using CDN

### ISSUE THREAD

**Issue by MegChai** [mgaitan/sphinxcontrib-mermaid#64]
I want to use this extension on an intranet server. It could not access any files from public networks including CDN (unpkg.com). Another suggestion is to use jsDelivr instead of unpkg which will improve the access speed in some area.

**Comment by gil-obradors** [comment]
The response of the answer is yes.

Manually copy the .js file and configure static files like https://github.com/mgaitan/sphinxcontrib-mermaid/blob/master/README#L129
