### ISSUE TITLE
Fails after updating to Sphinx 3.5.1 

### ISSUE THREAD

**Issue by championshuttler** [mgaitan/sphinxcontrib-mermaid#68]
Mermaid graphs are not rendering https://firefox-source-docs.mozilla.org/tools/moztreedocs/mermaid-integration.html after upgrading to 3.5.1 we are getting this errro `Uncaught ReferenceError: mermaid is not defined`

**Comment by gil-obradors** [comment]
Hi !

I have the same problem. But I fix it.

I can't found mermaid.js downloaded on _static files, so Sphinx doesn't download it.
So the browser doesn't load mermaid.js packages, and can't find mermaid.* references for rendering.

I have resolved it: 
- downloading the file from CDN `wget https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.9.1/mermaid.js`, 
- put it into _static/js` 
- and put this directive to config.py : `html_js_files = [
   'js/mermaid.js',
]
`


Check if it works for you!

I will try to find why isn't downloaded automatically, or create a PR advertiding of that on `readme.md`


Good luck!

**Comment by championshuttler** [comment]
Yeah we did the same in last but instead of downloading the js file i am rendering it directly https://searchfox.org/mozilla-central/source/docs/conf.py#77 , earlier we used to have this post script to render on every page https://phabricator.services.mozilla.com/D105674

**Comment by championshuttler** [comment]
> Hi !
> 
> I have the same problem. But I fix it.
> 
> I can't found `mermaid.js` downloaded on _static files, so Sphinx doesn't download it.
> So the browser doesn't load `mermaid.js` packages, and can't find mermaid.* references for rendering.
> 
> I have resolved it:
> 
> * downloading the file from CDN `wget https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.9.1/mermaid.js`,
> * put it into _static/js`
> * and put this directive to config.py : `html_js_files = [ 'js/mermaid.js', ] `
> 
> Check if it works for you!
> 
> I will try to find why isn't downloaded automatically, or create a PR advertising of that on `readme.md`
> 
> Good luck!

I guess in the latest Sphinx 3.5.1 they removed some functionality i am not sure though thats why sphinx is not able to find mermaid script in `_static`

**Comment by gil-obradors** [comment]
I think i found it.

@mgaitan  is posible that may be load mermaid js from cdn with this [register](https://www.sphinx-doc.org/en/1.8/extdev/appapi.html#sphinx.application.Sphinx.add_js_file)? 

https://github.com/mgaitan/sphinxcontrib-mermaid/blob/1af85206ee87d206445c06ea0cd532be16adad4d/sphinxcontrib/mermaid.py#L199

**Comment by mgaitan** [comment]
I've just committed a patch among a set of basic unit tests (finally!). Published 0.6.3 

@gil-obradors you were right, that was the problem but needed to do that not in the setup nor the actual node handler but in a special function called via "html-page-context" signal (doing it in the setup makes the tests with conf overrides to fail). 

I'm no sure if I've just broke compatibility with not so old sphinx versions I'd happily accept a PR to fix it if so).

**Comment by iancze** [comment]
I think I'm getting the same javascript error: `Uncaught ReferenceError: mermaid is not defined`. 

I'm using sphinxcontrib-mermaid v0.6.3 and sphinx v3.5.2 (though this also failed on 3.4.3 before I upgraded). I had stumbled upon the solution outlined by @gil-obradors , which allowed things to work locally, but ultimately failed when I pushed to readthedocs.

**Comment by gil-obradors** [comment]
I'm on `v0.6.2`,
I will try `v0.6.3` @iancze

**Comment by championshuttler** [comment]
In Production, same happening with me, I am getting same error as @iancze

**Comment by hsuominen** [comment]
Seeing the same issue here

**Comment by florianhumblot** [comment]
@mgaitan I've proposed a fix for this issue which should be a more permanent solution to the problem. 
Is there a way you can upstream the patch or fix it in another proposed way? 
The PR with the proposed fix is #77
