### ISSUE TITLE
sphinx-mermaid changes my page's CSS, sets "section" opacity to 0.2, results in my page content being semi-transparent.

### ISSUE THREAD

**Issue by Zulko** [mgaitan/sphinxcontrib-mermaid#7]
Sorry for the long title. everything is in it :smile: 
The moment I put a ``.. mermaid::`` in my page, the CSS changes and in particular the ``section`` tags (``opacity: 0.2``).
Looking into the code it seems that you are aware of this and there is a workaround in the code, but the pypi version still has this problem apparemtly.

**Comment by mgaitan** [comment]
Yeah, it's an issue in mermaid.  I raised a ticket there  knsv/mermaid#527. Check my workaround here b2740ea55cc8a73eea1a5ab41c10537b95ffa22c

**Comment by Zulko** [comment]
As I said, I have seen the workaround in the code, but the version I got from pip doesnt seem to work - is the workaround pushed on PyPI ?

**Comment by mgaitan** [comment]
oh sorry. yes, the hack is part of the tag 0.2, which is the last version released on pypi. But now I note it only apply to `.section` (the css class applied to `div` for example) and not for `section` as tag. Could you confirm this?

**Comment by Zulko** [comment]
Oh yes indeed. Now I understand the problem: I am using the popular [read-the-docs theme](http://docs.readthedocs.io/en/latest/theme.html) which uses ``section`` as a class for all the sections of the documentation. As a consequence everything gets the semi-opacity.

**Comment by iroller** [comment]
Hey @Zulko, did you figure out the way how to apply the workaround when using read-the-docs theme?

**Comment by iroller** [comment]
@mgaitan removing `.body` from your workaround would fix the issue for those using read-the-docs theme.

**Comment by mgaitan** [comment]
could you send a tiny PR?

**Comment by iroller** [comment]
@mgaitan of course. https://github.com/mgaitan/sphinxcontrib-mermaid/pull/8

**Comment by mgaitan** [comment]
fixed in 3baa0b2

**Comment by Zulko** [comment]
Just to confirm it works like a charm now. Thanks very much guys !
