### ISSUE TITLE
Upload source tarball to pypi for version 0.7

### ISSUE THREAD

**Issue by ericpre** [mgaitan/sphinxcontrib-mermaid#75]
As mentioned in https://github.com/conda-forge/sphinxcontrib-mermaid-feedstock/issues/5 and https://github.com/conda-forge/sphinxcontrib-mermaid-feedstock/pull/6, the source tarball are used by conda-forge to build the conda packages and it seems that the source tarball were not uploaded to pypi for sphinxcontrib-mermaid 0.7 - only the wheel have been uploaded.

Would it be possible to have the source tarball uploaded?

**Comment by mgaitan** [comment]
I've just released the version 0.7.1 in pypy as wheel and source.
