### ISSUE TITLE
Umlauts causing error on build

### ISSUE THREAD

**Issue by sgaechter** [mgaitan/sphinxcontrib-mermaid#81]
Umlauts, as common in German Language (like: ä, ö, ü) causing problems buildung Sphinx Docs. The infected Charts are replaced by "Syntax error in graph mermaid version 8.13.7":

Error Message displayed in Doc:
![Error](https://user-images.githubusercontent.com/29682065/149160343-56fb3874-6166-4923-997b-240432bd7007.png)

As soon as all umlauts are replaced, the graphs will be displayed as expected.
Tested ``make`` commands: html, latexpdf

Example:

`.. mermaid::

   flowchart LR
      a(Kundeninput) --> b(Product-Backlog) --> c(Sprintplanung) --> e("Sprint (2-4 Wochen)") --> f(Sprint-Review) --> g([Zum Veröffentlichungsprozess])
      e --> d(Sprint-Retrospektive) --> c`

When I build the mermaid chart with mermaid-cli the umlauts are built correct (see output.png below):
![output](https://user-images.githubusercontent.com/29682065/149161244-1a2cd9da-b3c3-4c52-b831-655052308c9a.png)

used version: Master (a6c1f8b9dc3e84cde8e2658856c0668dc47324db)

**Comment by mgaitan** [comment]
I've tested this and looks ok 

![Uploading image.png…]()

**Comment by sgaechter** [comment]
@mgaitan The Screenshot with the diagram you see in my Post is not the result in the rendered sphinx doc. I've rendered this with the online tool. Mermaid still throws an error and only the Error - Placeholder is shown in the doc.

**Comment by mgaitan** [comment]
@sgaechter the screenshot I've posted was after copying/pasting your diagram code in a .rst file and then building html with sphinx. Is it not the issue reported?
In such a case, could you share an online example of a source and the produced html

**Comment by sgaechter** [comment]
@mgaitan I tested the output again.  Unfortunately, either the HTML or latexpdf is rendered correctly on my side:
**Source**
![meermaid sourcecode](https://user-images.githubusercontent.com/29682065/188810556-85165e0f-9aa9-498b-b76e-74211a1773b1.png)
**HTML:**
![meermaid-Chart html](https://user-images.githubusercontent.com/29682065/188810756-a5247ce3-b810-49dc-a249-ba74f5b3fafe.png)

**latexpdf:**
![meermaid-Chart latexpdf](https://user-images.githubusercontent.com/29682065/188810954-1f270e85-2360-4581-811e-9a9caa16e6f0.png)

as soon as I replace the umlaut "ö" to "oe " the rendering works as expected:
**HTML:**
![mermaid-Chart html_noumlauts](https://user-images.githubusercontent.com/29682065/188811558-a50a901b-0012-4621-9db9-2a0ecdd7063d.png)

**latexpfdf**
![mermaid-Chart latexpdf_noumlauts](https://user-images.githubusercontent.com/29682065/188811904-76e6fa98-434e-4ba9-a6ae-8d0709d4afca.png)

Attached you can find the full source code of the sphinx-Project. I'd be pleased if somebody can tell me what's wrong.
[source.zip](https://github.com/mgaitan/sphinxcontrib-mermaid/files/9503959/source.zip)

Used versions in requirements.txt

Thanks
Sven
[source.zip](https://github.com/mgaitan/sphinxcontrib-mermaid/files/9503959/source.zip)

**Comment by sgaechter** [comment]
Issue still open also with latest release.

**Comment by cstmth** [comment]
This is still a problem. The following line in a sankey-beta diagram causes a Diagram syntax error:

`Kein Angebot, hätte angenommen, 3`

`Error: Error: Parse error on line 17:
...t, 1Kein Angebot, hätte angenommen, 3
----------------------^
Expecting 'NEWLINE', 'EOF', 'COMMA', got 'NON_ESCAPED_TEXT'`

**Comment by MrApe** [comment]
Same problem here... It's almost 2025 and encoding is still an issue...

**Comment by timkpaine** [comment]
> Same problem here... It's almost 2025 and encoding is still an issue...

You should ask for your money back!

**Comment by timkpaine** [comment]
tested on latest version, works fine for me. User error.
