### ISSUE TITLE
Whitespace between text and sequence diagram

### ISSUE THREAD

**Issue by kevin-bates** [mgaitan/sphinxcontrib-mermaid#82]
Hello - this is a great project - thank you for maintaining it!

I'm not sure if this is a known issue (not really finding references to it in the issues or pull requests) and I could very well be doing something wrong (fairly new to sphinx and sphinx extensions in general).

When I add a sequence diagram to a markdown file, there's always a gap of whitespace between the text on the page and the diagram, about the same size as what the instructions take.  In addition, when I refresh the page, I see the instructions flash in the whitespace area.  (See gif) Is there some configuration step I'm missing or a way to resolve these issues?  (The whitespace being more troubling than the flash of instructions.)

![MermaidWhitespaceRefreshIssue](https://user-images.githubusercontent.com/22599560/155025473-1282f82c-07d4-4b34-86fa-a975ed6ed7de.gif)

<details>
  <summary>Here's the markdown as well:</summary>
# Example Mermaid Sequence Diagram

Here's an example Mermaid Sequence Diagram. Note the whitespace between this paragraph and the diagram.  Also, note how the diagram's instructions are briefly visible on refresh.  Is this a known issue?

```{mermaid}
sequenceDiagram
    participant ModuleA
    participant ModuleB
    participant ModuleC
    participant ModuleD
    participant ModuleE
    participant ModuleF
    Note left of ModuleA: fetch widgets
    ModuleA->>ModuleB: https GET api/widgets
    ModuleB->>ModuleC: https GET api/widgets
    ModuleC-->>ModuleB: api/widgets response
    ModuleB-->>ModuleA: api/widgets response

    Note left of ModuleA: snippet init
    ModuleA->>ModuleB: https POST api/gadgets
    ModuleB->>ModuleC: https POST api/snippets
    ModuleC->>ModuleD: launch_process()
    ModuleD->>ModuleE: launch snippet
    ModuleD->>ModuleF: confirm startup
    ModuleE-->>ModuleD: connection info
    ModuleF-->>ModuleD: state & host info
    ModuleD-->>ModuleC: complete connection info
    ModuleC->>ModuleE: TCP socket requests
    ModuleE-->>ModuleC: TCP socket handshakes
    ModuleC-->>ModuleB: api/snippets response
    ModuleB-->>ModuleA: api/gadgets response

    ModuleA->>ModuleB: ws GET api/snippets
    ModuleB->>ModuleC: ws GET api/snippets
    ModuleC-->>ModuleB: websocket upgrade response
    ModuleB-->>ModuleA: websocket upgrade response
```

Note: the backticks on the `mermaid` directive and closing backticks are not showing up.  I'm using the myst-parser with a syntax identical to what's on [this page](https://myst-parser.readthedocs.io/en/latest/sphinx/intro.html?highlight=mermaid#install-a-new-sphinx-extension-and-use-its-functionality).
</details>

**Comment by maldag** [comment]
Using the svg options yields to an `svg` element in the html view for me. Changing the height attribute to `100%` could reduce the whitespace. Adding an css element would be able to override the height attribute as a hack (but also for other rendered svg elements):

```
svg {
    height: auto;
}
```

**Comment by tchaikov** [comment]
thanks @maldag ! i added

```css
.mermaid svg {
    height: 100%;
}
```

in my `custom.css`. this works great for me.

**Comment by kevin-bates** [comment]
Thank you @tchaikov (and @maldag)!  This `custom.css` entry works for me as well.  I still see a brief flash of the markdown, but that is tolerable - thank you.

Since this seems like a reasonable workaround, I'm going to close the issue.
