### ISSUE TITLE
Cannot set 'mermaid_cmd' to multiple words

### ISSUE THREAD

**Issue by slanzmich** [mgaitan/sphinxcontrib-mermaid#89]
Currently, `mermaid_cmd` cannot be set to a command containing arguments / multiple words, e.g. `npx mmdc`. Neither
```python
mermaid_cmd = "npx mmdc"
```
nor
```python
mermaid_cmd = ["npx", "mmdc"]
```
work, because the command is always passed as first item of a list to `os.Popen`.

What do you think about always supporting the second form, and support the first form (by calling `shlex.split` on string input) if `mermaid_cmd_shell` is set?

**Comment by mgaitan** [comment]
hey @slanzmich , that sounds ok. could you send a PR?

**Comment by Gabrielcarvfer** [comment]
@mgaitan #79 does that. :)

**Comment by slanzmich** [comment]
Right, #79 would solve my issue. On the other hand, always splitting the string will break things for people specifying a path containing spaces. To support both, a list of strings should also be accepted. I'll send a PR.

**Comment by slanzmich** [comment]
I opened #91 with an alternative implementation.

**Comment by tuncbkose** [comment]
I could also use this

**Comment by mgaitan** [comment]
could somebody update the pr to resolve the conflicts?

**Comment by tuncbkose** [comment]
Hmm, the conflicts seem easy to fix but I'm not sure how to do that without access to @slanzmich's repo. Would it work if I forked their repo and made a separate pr?

**Comment by mgaitan** [comment]
@tuncbkose sure!

**Comment by tuncbkose** [comment]
Thank you! Any idea when there may be a new version release?
