### ISSUE TITLE
Issue with centering and caption

### ISSUE THREAD

**Issue by barriern** [mgaitan/sphinxcontrib-mermaid#90]
Hi everyone.

I have an issue when trying to rendering a Mermaid graph as follows:

```
.. mermaid:: _static/mermaid/scheduling.md
    :caption: Blabla
    :align: center
```
In this case, the graph is not centered in HTML outputs (but it is in latexpdf). If I remove the caption, it works fine. Does anyone know how to fix this?

Here is the version I use:

```
sphinxcontrib-mermaid     0.7.1              pyhd8ed1ab_0    conda-forge
```

Thanks

Nicolas

**Comment by mgaitan** [comment]
hello @barriern . I've tried to reproduce it and I couldn't 

![image](https://user-images.githubusercontent.com/2355719/187054492-7fd12c73-dac9-4da5-be80-548083d2191e.png)

as you can see, the figure wrapper is created correctly. Then it depends on your theme CSS how that's handled.

I'm curious, is the way it looks like different if you define a `.. figure` with caption and align?

**Comment by barriern** [comment]
Hi @mgaitan 

It seems to be due to an outdated Sphinx RTD theme. Using default theme worked fine, and updating the RTD theme also solved the problem. Sorry for the inconvenience.

Nicolas
