### ISSUE TITLE
Enable myst-parser mermaid rendering without curly braces in markdown

### ISSUE THREAD

**Issue by d33bs** [mgaitan/sphinxcontrib-mermaid#99]
Thank you for the great work within this project! In working with mermaid diagrams through this extension and [myst-parser](https://github.com/executablebooks/MyST-Parser) within markdown files I've noticed a minor detail which might assist developers as they draft or review content.

When using this extension via myst-parser in markdown files, one is required to use the following format:
````markdown
```{mermaid}
<diagram content>
```
````

Some editors and interfaces, such as Github ([see here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams)), enable the rendering of mermaid without building it Sphinx. This format relies on a similar codeblock that does not use curly braces, as seen below:
````markdown
```mermaid
<diagram content>
```
````

Using a format which does not rely on curly braces would allow developers referencing mermaid content on platforms like Github to easily view both the rendered output and the code which rendered the output. Is this something which is possible through additional configuration or code with this extension? Thank you in advance for your thoughts and feedback on this topic.

Please note: I was unsure whether it'd be more appropriate to open an issue here or with the myst-parser project. Please don't hesitate to let me know if I may reference this topic elsewhere, or upvote an existing issue, thank you!

**Comment by bilderbuchi** [comment]
I agree, this would indeed be useful to have! It would make reviewing/discussing PRs much more streamlined if the mermaid diagrams were rendered in the PR files/diff view, and I think using the brace-less syntax should achieve that.

**Comment by bilderbuchi** [comment]
See also https://github.com/executablebooks/MyST-Parser/issues/366#issuecomment-1239679922

**Comment by ggydush** [comment]
+1 to this feature, would be a great improvement!

**Comment by vppillai** [comment]
+1 to this feature.

**Comment by dustinlagoy** [comment]
Note https://github.com/executablebooks/MyST-Parser/issues/366 has been fixed by https://github.com/executablebooks/MyST-Parser/pull/742 which I believe also fixes this issue.

**Comment by rjohnkraemer** [comment]
+1 to this, would also like to see

.. mermaid :: 
<diagram content>
:::

**Comment by timkpaine** [comment]
The original ask can be done with `myst_fence_as_directive = ["mermaid"]`

https://github.com/python-project-templates/yardang/blob/ac6c1df992d56296d2f6fe375a04fcb81f5f7ed6/yardang/conf.py.j2#L78

**Comment by timkpaine** [comment]
closing as won't fix since the above works
